import("//build/lib.gni")

copy("fix-ll.py") {
  sources = ["fix-ll.py"]
  outputs = ["$root_build_dir/${sources[0]}"]
}

copy("fix-ebnf.sh") {
  sources = ["fix-ebnf.sh"]
  outputs = ["$root_build_dir/${sources[0]}"]
  deps = [":fix-ll.py"]
}

action("Parser.ebnf") {
  outputs = [ "$target_gen_dir/$target_name" ]
  script = "//build/exec.sh"
  sources = [ "$root_build_dir/cocor-cpp", "$root_gen_dir/build/boogie/Source/Core/BoogiePL.atg" ]
  inputs = [ "./frames" ]

  args = rebase_path(sources) + [
    "-genRREBNF",
    "-frames",
  ] + rebase_path(inputs) + [
    "-o",
    rebase_path(target_gen_dir)
  ]

  deps = ["//build/boogie", "//build/cocor-cpp"]
}

action("boogie.ebnf.orig") {
  outputs = [ "$root_build_dir/$target_name" ]
  script = "//build/exec.sh"
  sources = [ "$target_gen_dir/Parser.ebnf" ]
  inputs = [ "$root_build_dir/fix-ebnf.sh" ]

  args = rebase_path(inputs + sources + outputs)

  deps = [":Parser.ebnf", ":fix-ebnf.sh"]
}

action("boogie.ebnf") {
  outputs = [ "$root_build_dir/$target_name" ]
  script = "//build/exec.sh"
  sources = [ "$root_build_dir/boogie.ebnf.orig" ]
  inputs = [ "fix-ebnf.diff" ]

  args =
    [ "patch", "--verbose", "--merge" ]
    + [ "--output" ] + rebase_path(outputs)
    + [ "-i" ] + rebase_path(inputs)
    + rebase_path(sources)

  deps = [ ":boogie.ebnf.orig" ]
}

action("grammar.js.orig") {
  outputs = [ "$root_build_dir/$target_name" ]
  script = "//build/exec.sh"
  sources = [ "$root_build_dir/boogie.ebnf" ]
  inputs = [ "$root_gen_dir/build/ts-ebnf-gen/src/lua/parse_grammar.lua" ]

  args =
    [ "bash", "-c", "\$0 \$1 > \$2" ]
    + rebase_path(inputs + sources + outputs, root_build_dir)

  deps = [ ":boogie.ebnf", "//build/ts-ebnf-gen" ]
}

action("grammar.js") {
  outputs = [ "$root_build_dir/$target_name" ]
  script = "//build/exec.sh"
  sources = [ "$root_build_dir/grammar.js.orig" ]
  inputs = [ "fix-grammar.sh" ]

  args = rebase_path(inputs + sources + outputs)

  deps = [ ":grammar.js.orig" ]
}


action("rr.ebnf") {
  outputs = [ "$root_build_dir/$target_name" ]
  script = "//build/exec.sh"
  sources = [ "$target_gen_dir/Parser.ebnf" ]
  inputs = [ "to-hash-x.sh" ]

  args =
    [ "bash", "-c", "\$0 < \$1 > \$2" ]
    + rebase_path(inputs + sources + outputs)

  deps = [ ":Parser.ebnf", "//build/ts-ebnf-gen" ]
}

action("rr.zip") {
  outputs = [ "$root_build_dir/$target_name" ]
  script = "//build/exec.sh"
  sources = [ "$root_build_dir/rr.ebnf" ]
  inputs = [ "$root_gen_dir/build/rr/rr-webapp-2.6.war" ]

  rebase_out = rebase_path(outputs[0])

  args =
    [ "java", "-jar" ] + rebase_path(inputs)
    + [ "-html", "-noembedded", "-out:$rebase_out" ]
    + rebase_path(sources)

  deps = [ ":rr.ebnf", "//build/rr" ]
}
