[package]
name = "tree-sitter-boogie"
description = "Tree-sitter grammar for the Boogie IVL"
version = "0.1.0"
authors = ["Kait Lam"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "boogie"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/tree-sitter/tree-sitter-boogie"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.25.3"
