/**
	* @file Tree-sitter grammar for the Boogie IVL
	* @author Kait Lam
	* @license MPL-2.0
	*/

/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at https://mozilla.org/MPL/2.0/.
*/

const regexseq = (...args) => new RegExp("(?:" + args.map(x => x.source).join("") + ")");
const regexrepeat = (arg) => new RegExp("(?:" + arg.source + ")*");
const regexchoice = (...args) => new RegExp("(?:" + args.map(x => x.source).join("|") + ")");
const regexoptional = arg => new RegExp("(?:" + arg + ")?");


// This file was autogenerated by parse_grammar.lua from boogie.ebnf.

/*
 * inline constants:
 */

module.exports = grammar({
  name: 'boogie',

  /*
   * boogie.ebnf:1
   * extras ::= { comment /\s+/ }
   */
  extras: $ =>
    [$.comment, /\s+/],
  /*
   * boogie.ebnf:3
   * conflicts ::= { { Type } { TypeArgs } }
   */
  conflicts: $ =>
    [[$.Type], [$.TypeArgs]],
  /*
   * boogie.ebnf:5
   * word ::= ident
   */
  word: $ =>
    $.ident,
  rules: {
    /*
     * boogie.ebnf:14
     * BoogiePL ::=  ( Consts | Function | Axiom | UserDefinedTypes | Datatype | GlobalVars | InvariantDecl | "yield" ( InvariantDecl | YieldProcedureDecl ) | Pure ( Procedure | ActionDecl ) | Implementation )*
     */
    BoogiePL: $ =>
      repeat(
        choice(
          $.Consts,
          $.Function,
          $.Axiom,
          $.UserDefinedTypes,
          $.Datatype,
          $.GlobalVars,
          $.InvariantDecl,
          seq("yield", choice($.InvariantDecl, $.YieldProcedureDecl)),
          seq(optional($.Pure), choice($.Procedure, $.ActionDecl)),
          $.Implementation
        )
      ),
    /*
     * boogie.ebnf:15
     * Consts ::=  "const" Attribute* ( "unique" )? IdsType ( ";" | "uses" "{" ( Axiom )* "}" )
     */
    Consts: $ =>
      seq(
        "const",
        repeat($.Attribute),
        optional("unique"),
        $.IdsType,
        choice(";", seq("uses", "{", repeat($.Axiom), "}"))
      ),
    /*
     * boogie.ebnf:16
     * Function ::=  ( "revealed" )? "function" Attribute* Ident TypeParams? "(" ( VarOrType ( "," VarOrType )* )? ")" ( "returns" "(" VarOrType ")" | ":" Type ) ( "{" Expression "}" ( "uses" "{" ( Axiom )* "}" )? | "uses" "{" ( Axiom )* "}" | ";" )
     */
    Function: $ =>
      seq(
        optional("revealed"),
        "function",
        repeat($.Attribute),
        $.Ident,
        optional($.TypeParams),
        "(",
        optional(seq($.VarOrType, repeat(seq(",", $.VarOrType)))),
        ")",
        choice(seq("returns", "(", $.VarOrType, ")"), seq(":", $.Type)),
        choice(
          seq("{", $.Expression, "}", optional(seq("uses", "{", repeat($.Axiom), "}"))),
          seq("uses", "{", repeat($.Axiom), "}"),
          ";"
        )
      ),
    /*
     * boogie.ebnf:17
     * Axiom ::=  ( "hideable" )? "axiom" Attribute* Proposition ";"
     */
    Axiom: $ =>
      seq(optional("hideable"), "axiom", repeat($.Attribute), $.Proposition, ";"),
    /*
     * boogie.ebnf:18
     * UserDefinedTypes ::=  "type" Attribute* UserDefinedType ( "," UserDefinedType )* ";"
     */
    UserDefinedTypes: $ =>
      seq(
        "type",
        repeat($.Attribute),
        $.UserDefinedType,
        repeat(seq(",", $.UserDefinedType)),
        ";"
      ),
    /*
     * boogie.ebnf:19
     * Datatype ::=  "datatype" Attribute* Ident TypeParams? "{" Constructors "}"
     */
    Datatype: $ =>
      seq(
        "datatype",
        repeat($.Attribute),
        $.Ident,
        optional($.TypeParams),
        "{",
        $.Constructors,
        "}"
      ),
    /*
     * boogie.ebnf:20
     * GlobalVars ::=  "var" Attribute* IdsTypeWheres ";"
     */
    GlobalVars: $ =>
      seq("var", repeat($.Attribute), $.IdsTypeWheres, ";"),
    /*
     * boogie.ebnf:21
     * InvariantDecl ::=  "invariant" Attribute* Ident ProcFormals ";" Invariant*
     */
    InvariantDecl: $ =>
      seq(
        "invariant",
        repeat($.Attribute),
        $.Ident,
        $.ProcFormals,
        ";",
        repeat($.Invariant)
      ),
    /*
     * boogie.ebnf:22
     * YieldProcedureDecl ::=  MoverQualifier? "procedure" Attribute* Ident ProcFormals ( "returns" ProcFormals )? ( ";" SpecYieldPrePost* | SpecYieldPrePost* ImplBody )
     */
    YieldProcedureDecl: $ =>
      seq(
        optional($.MoverQualifier),
        "procedure",
        repeat($.Attribute),
        $.Ident,
        $.ProcFormals,
        optional(seq("returns", $.ProcFormals)),
        choice(
          seq(";", repeat($.SpecYieldPrePost)),
          seq(repeat($.SpecYieldPrePost), $.ImplBody)
        )
      ),
    /*
     * boogie.ebnf:23
     * Pure ::=  ( "pure" )?
     */
    Pure: $ =>
      ("pure"),
    /*
     * boogie.ebnf:24
     * Procedure ::=  "procedure" ProcSignature ( ";" Spec* | Spec* ImplBody )
     */
    Procedure: $ =>
      seq(
        "procedure",
        $.ProcSignature,
        choice(seq(";", repeat($.Spec)), seq(repeat($.Spec), $.ImplBody))
      ),
    /*
     * boogie.ebnf:25
     * ActionDecl ::=  MoverQualifier? "action" Attribute* Ident ProcFormals ( "returns" ProcFormals )? ( ";" SpecAction* | SpecAction* ImplBody )
     */
    ActionDecl: $ =>
      seq(
        optional($.MoverQualifier),
        "action",
        repeat($.Attribute),
        $.Ident,
        $.ProcFormals,
        optional(seq("returns", $.ProcFormals)),
        choice(seq(";", repeat($.SpecAction)), seq(repeat($.SpecAction), $.ImplBody))
      ),
    /*
     * boogie.ebnf:26
     * Implementation ::=  "implementation" ProcSignature ImplBody
     */
    Implementation: $ =>
      seq("implementation", $.ProcSignature, $.ImplBody),
    /*
     * boogie.ebnf:27
     * Attribute ::=  AttributeOrTrigger
     */
    Attribute: $ =>
      $.AttributeOrTrigger,
    /*
     * boogie.ebnf:28
     * IdsTypeWheres ::=  IdsTypeWhere ( "," IdsTypeWhere )*
     */
    IdsTypeWheres: $ =>
      seq($.IdsTypeWhere, repeat(seq(",", $.IdsTypeWhere))),
    /*
     * boogie.ebnf:29
     * LocalVars ::=  "var" Attribute* IdsTypeWheres ";"
     */
    LocalVars: $ =>
      seq("var", repeat($.Attribute), $.IdsTypeWheres, ";"),
    /*
     * boogie.ebnf:30
     * ProcFormals ::=  "(" AttributesIdsTypeWheres? ")"
     */
    ProcFormals: $ =>
      seq("(", optional($.AttributesIdsTypeWheres), ")"),
    /*
     * boogie.ebnf:31
     * AttributesIdsTypeWheres ::=  AttributesIdsTypeWhere ( "," AttributesIdsTypeWhere )*
     */
    AttributesIdsTypeWheres: $ =>
      seq($.AttributesIdsTypeWhere, repeat(seq(",", $.AttributesIdsTypeWhere))),
    /*
     * boogie.ebnf:32
     * BoundVars ::=  AttributesIdsTypeWheres
     */
    BoundVars: $ =>
      $.AttributesIdsTypeWheres,
    /*
     * boogie.ebnf:33
     * IdsType ::=  Idents ":" Type
     */
    IdsType: $ =>
      seq($.Idents, ":", $.Type),
    /*
     * boogie.ebnf:34
     * Idents ::=  Ident ( "," Ident )*
     */
    Idents: $ =>
      seq($.Ident, repeat(seq(",", $.Ident))),
    /*
     * boogie.ebnf:35
     * Type ::=  ( TypeAtom | Ident TypeArgs? | MapType )
     */
    Type: $ =>
      choice($.TypeAtom, seq($.Ident, optional($.TypeArgs)), $.MapType),
    /*
     * boogie.ebnf:36
     * AttributesIdsTypeWhere ::=  Attribute* IdsTypeWhere
     */
    AttributesIdsTypeWhere: $ =>
      seq(repeat($.Attribute), $.IdsTypeWhere),
    /*
     * boogie.ebnf:37
     * IdsTypeWhere ::=  Idents ":" Type ( "where" Expression )?
     */
    IdsTypeWhere: $ =>
      seq($.Idents, ":", $.Type, optional(seq("where", $.Expression))),
    /*
     * boogie.ebnf:38
     * Expression ::=  ImpliesExpression ( EquivOp ImpliesExpression )*
     */
    Expression: $ =>
      seq($.ImpliesExpression, repeat(seq($.EquivOp, $.ImpliesExpression))),
    /*
     * boogie.ebnf:39
     * TypeAtom ::=  ( "int" | "real" | "bool" | "(" Type ")" )
     */
    TypeAtom: $ =>
      choice("int", "real", "bool", seq("(", $.Type, ")")),
    /*
     * boogie.ebnf:40
     * Ident ::=  ( ident | "atomic" | "both" | "left" | "right" | "reveal" | "hide" | "push" | "pop" )
     */
    Ident: $ =>
      choice($.ident, "atomic", "both", "left", "right", "reveal", "hide", "push", "pop"),
    /*
     * boogie.ebnf:41
     * TypeArgs ::=  ( TypeAtom TypeArgs? | Ident TypeArgs? | MapType )
     */
    TypeArgs: $ =>
      choice(
        seq($.TypeAtom, optional($.TypeArgs)),
        seq($.Ident, optional($.TypeArgs)),
        $.MapType
      ),
    /*
     * boogie.ebnf:42
     * MapType ::=  ( TypeParams )? "[" Types? "]" Type
     */
    MapType: $ =>
      seq(optional($.TypeParams), "[", optional($.Types), "]", $.Type),
    /*
     * boogie.ebnf:43
     * TypeParams ::=  "<" Idents ">"
     */
    TypeParams: $ =>
      seq("<", $.Idents, ">"),
    /*
     * boogie.ebnf:44
     * Types ::=  Type ( "," Type )*
     */
    Types: $ =>
      seq($.Type, repeat(seq(",", $.Type))),
    /*
     * boogie.ebnf:45
     * VarOrType ::=  Attribute* Type ( ":" Type )?
     */
    VarOrType: $ =>
      seq(repeat($.Attribute), $.Type, optional(seq(":", $.Type))),
    /*
     * boogie.ebnf:46
     * Proposition ::=  Expression
     */
    Proposition: $ =>
      $.Expression,
    /*
     * boogie.ebnf:47
     * UserDefinedType ::=  Ident WhiteSpaceIdents? ( "=" Type )?
     */
    UserDefinedType: $ =>
      seq($.Ident, optional($.WhiteSpaceIdents), optional(seq("=", $.Type))),
    /*
     * boogie.ebnf:48
     * WhiteSpaceIdents ::=  Ident ( Ident )*
     */
    WhiteSpaceIdents: $ =>
      seq($.Ident, repeat($.Ident)),
    /*
     * boogie.ebnf:49
     * Constructors ::=  Constructor ( "," Constructor )*
     */
    Constructors: $ =>
      seq($.Constructor, repeat(seq(",", $.Constructor))),
    /*
     * boogie.ebnf:50
     * Constructor ::=  Ident "(" AttributesIdsTypeWheres? ")"
     */
    Constructor: $ =>
      seq($.Ident, "(", optional($.AttributesIdsTypeWheres), ")"),
    /*
     * boogie.ebnf:51
     * Invariant ::=  "preserves" Attribute* Proposition ";"
     */
    Invariant: $ =>
      seq("preserves", repeat($.Attribute), $.Proposition, ";"),
    /*
     * boogie.ebnf:52
     * MoverQualifier ::=  "left" | "right" | "both" | "atomic"
     */
    MoverQualifier: $ =>
      choice("left", "right", "both", "atomic"),
    /*
     * boogie.ebnf:53
     * SpecAction ::=  SpecRefinedActionForAtomicAction | SpecModifies | SpecYieldRequires | SpecAsserts
     */
    SpecAction: $ =>
      choice(
        $.SpecRefinedActionForAtomicAction,
        $.SpecModifies,
        $.SpecYieldRequires,
        $.SpecAsserts
      ),
    /*
     * boogie.ebnf:54
     * ImplBody ::=  "{" LocalVars* StmtList
     */
    ImplBody: $ =>
      seq("{", repeat($.LocalVars), $.StmtList),
    /*
     * boogie.ebnf:55
     * SpecRefinedActionForAtomicAction ::=  "refines" Attribute* Ident ";"
     */
    SpecRefinedActionForAtomicAction: $ =>
      seq("refines", repeat($.Attribute), $.Ident, ";"),
    /*
     * boogie.ebnf:56
     * SpecRefinedActionForYieldProcedure ::=  "refines" Attribute* ( MoverQualifier? "action" Attribute* Ident ImplBody | Ident ";" )
     */
    SpecRefinedActionForYieldProcedure: $ =>
      seq(
        "refines",
        repeat($.Attribute),
        choice(
          seq(optional($.MoverQualifier), "action", repeat($.Attribute), $.Ident, $.ImplBody),
          seq($.Ident, ";")
        )
      ),
    /*
     * boogie.ebnf:57
     * SpecModifies ::=  "modifies" ( Idents )? ";"
     */
    SpecModifies: $ =>
      seq("modifies", optional($.Idents), ";"),
    /*
     * boogie.ebnf:58
     * SpecYieldRequires ::=  "requires" ( Attribute* Proposition | CallCmd ) ";"
     */
    SpecYieldRequires: $ =>
      seq("requires", choice(seq(repeat($.Attribute), $.Proposition), $.CallCmd), ";"),
    /*
     * boogie.ebnf:59
     * SpecAsserts ::=  "asserts" Attribute* Proposition ";"
     */
    SpecAsserts: $ =>
      seq("asserts", repeat($.Attribute), $.Proposition, ";"),
    /*
     * boogie.ebnf:60
     * SpecYieldPrePost ::=  SpecRefinedActionForYieldProcedure | SpecYieldRequires | SpecYieldPreserves | SpecYieldEnsures | SpecYieldMeasure | SpecModifies
     */
    SpecYieldPrePost: $ =>
      choice(
        $.SpecRefinedActionForYieldProcedure,
        $.SpecYieldRequires,
        $.SpecYieldPreserves,
        $.SpecYieldEnsures,
        $.SpecYieldMeasure,
        $.SpecModifies
      ),
    /*
     * boogie.ebnf:61
     * CallCmd ::=  ( "async" )? ( "free" )? "call" CallParams ( "|" CallParams )*
     */
    CallCmd: $ =>
      seq(
        optional("async"),
        optional("free"),
        "call",
        $.CallParams,
        repeat(seq("|", $.CallParams))
      ),
    /*
     * boogie.ebnf:62
     * SpecYieldPreserves ::=  "preserves" ( Attribute* Proposition | CallCmd ) ";"
     */
    SpecYieldPreserves: $ =>
      seq("preserves", choice(seq(repeat($.Attribute), $.Proposition), $.CallCmd), ";"),
    /*
     * boogie.ebnf:63
     * SpecYieldEnsures ::=  "ensures" ( Attribute* Proposition | CallCmd ) ";"
     */
    SpecYieldEnsures: $ =>
      seq("ensures", choice(seq(repeat($.Attribute), $.Proposition), $.CallCmd), ";"),
    /*
     * boogie.ebnf:64
     * SpecYieldMeasure ::=  "measure" Attribute* Proposition ";"
     */
    SpecYieldMeasure: $ =>
      seq("measure", repeat($.Attribute), $.Proposition, ";"),
    /*
     * boogie.ebnf:65
     * ProcSignature ::=  Attribute* Ident TypeParams? ProcFormals ( "returns" ProcFormals )?
     */
    ProcSignature: $ =>
      seq(
        repeat($.Attribute),
        $.Ident,
        optional($.TypeParams),
        $.ProcFormals,
        optional(seq("returns", $.ProcFormals))
      ),
    /*
     * boogie.ebnf:66
     * Spec ::=  SpecModifies | "free" SpecPrePost | SpecPrePost
     */
    Spec: $ =>
      choice($.SpecModifies, seq("free", $.SpecPrePost), $.SpecPrePost),
    /*
     * boogie.ebnf:67
     * SpecPrePost ::=  ( "requires" Attribute* Proposition ";" | "ensures" Attribute* Proposition ";" | "measure" Attribute* Proposition ";" )
     */
    SpecPrePost: $ =>
      choice(
        seq("requires", repeat($.Attribute), $.Proposition, ";"),
        seq("ensures", repeat($.Attribute), $.Proposition, ";"),
        seq("measure", repeat($.Attribute), $.Proposition, ";")
      ),
    /*
     * boogie.ebnf:68
     * StmtList ::=  ( LabelOrCmd | StructuredCmd | TransferCmd )* "}"
     */
    StmtList: $ =>
      seq(repeat(choice($.LabelOrCmd, $.StructuredCmd, $.TransferCmd)), "}"),
    /*
     * boogie.ebnf:69
     * LabelOrCmd ::=  ( ( "reveal" | "hide" ) ( ident | "*" ) ";" | "pop" ";" | "push" ";" | LabelOrAssign | "assert" Attribute* Proposition ";" | "assume" Attribute* Proposition ";" | "havoc" Idents ";" | CallCmd ";" )
     */
    LabelOrCmd: $ =>
      choice(
        seq(choice("reveal", "hide"), choice($.ident, "*"), ";"),
        seq("pop", ";"),
        seq("push", ";"),
        $.LabelOrAssign,
        seq("assert", repeat($.Attribute), $.Proposition, ";"),
        seq("assume", repeat($.Attribute), $.Proposition, ";"),
        seq("havoc", $.Idents, ";"),
        seq($.CallCmd, ";")
      ),
    /*
     * boogie.ebnf:70
     * StructuredCmd ::=  ( IfCmd | WhileCmd | BreakCmd )
     */
    StructuredCmd: $ =>
      choice($.IfCmd, $.WhileCmd, $.BreakCmd),
    /*
     * boogie.ebnf:71
     * TransferCmd ::=  ( "goto" Attribute* Idents | "return" Attribute* ) ";"
     */
    TransferCmd: $ =>
      seq(
        choice(seq("goto", repeat($.Attribute), $.Idents), seq("return", repeat($.Attribute))),
        ";"
      ),
    /*
     * boogie.ebnf:72
     * IfCmd ::=  "if" Attribute* Guard "{" StmtList ( "else" ( IfCmd | "{" StmtList ) )?
     */
    IfCmd: $ =>
      seq(
        "if",
        repeat($.Attribute),
        $.Guard,
        "{",
        $.StmtList,
        optional(seq("else", choice($.IfCmd, seq("{", $.StmtList))))
      ),
    /*
     * boogie.ebnf:73
     * WhileCmd ::=  "while" Guard ( ( "free" )? "invariant" Attribute* ( Expression | CallCmd ) ";" )* "{" StmtList
     */
    WhileCmd: $ =>
      seq(
        "while",
        $.Guard,
        repeat(
          seq(
            optional("free"),
            "invariant",
            repeat($.Attribute),
            choice($.Expression, $.CallCmd),
            ";"
          )
        ),
        "{",
        $.StmtList
      ),
    /*
     * boogie.ebnf:74
     * BreakCmd ::=  "break" ( Ident )? ";"
     */
    BreakCmd: $ =>
      seq("break", optional($.Ident), ";"),
    /*
     * boogie.ebnf:75
     * Guard ::=  "(" ( "*" | Expression ) ")"
     */
    Guard: $ =>
      seq("(", choice("*", $.Expression), ")"),
    /*
     * boogie.ebnf:76
     * LabelOrAssign ::=  Ident ( ":" | "(" Idents ")" ":=" Attribute* Expression ";" | ( MapAssignIndex | FieldAccess )* ( "," Ident ( MapAssignIndex | FieldAccess )* )* ":=" Attribute* Expression ( "," Expression )* ";" )
     */
    LabelOrAssign: $ =>
      seq(
        $.Ident,
        choice(
          ":",
          seq("(", $.Idents, ")", ":=", repeat($.Attribute), $.Expression, ";"),
          seq(
            repeat(choice($.MapAssignIndex, $.FieldAccess)),
            repeat(seq(",", $.Ident, repeat(choice($.MapAssignIndex, $.FieldAccess)))),
            ":=",
            repeat($.Attribute),
            $.Expression,
            repeat(seq(",", $.Expression)),
            ";"
          )
        )
      ),
    /*
     * boogie.ebnf:77
     * MapAssignIndex ::=  "[" ( Expression ( "," Expression )* )? "]"
     */
    MapAssignIndex: $ =>
      seq("[", optional(seq($.Expression, repeat(seq(",", $.Expression)))), "]"),
    /*
     * boogie.ebnf:78
     * FieldAccess ::=  "->" Ident
     */
    FieldAccess: $ =>
      seq("->", $.Ident),
    /*
     * boogie.ebnf:79
     * CallParams ::=  Attribute* Ident ( "(" ( Expression ( "," Expression )* )? ")" | ( "," Ident ( "," Ident )* )? ":=" Ident "(" ( Expression ( "," Expression )* )? ")" )
     */
    CallParams: $ =>
      seq(
        repeat($.Attribute),
        $.Ident,
        choice(
          seq("(", optional(seq($.Expression, repeat(seq(",", $.Expression)))), ")"),
          seq(
            optional(seq(",", $.Ident, repeat(seq(",", $.Ident)))),
            ":=",
            $.Ident,
            "(",
            optional(seq($.Expression, repeat(seq(",", $.Expression)))),
            ")"
          )
        )
      ),
    /*
     * boogie.ebnf:80
     * Expressions ::=  Expression ( "," Expression )*
     */
    Expressions: $ =>
      seq($.Expression, repeat(seq(",", $.Expression))),
    /*
     * boogie.ebnf:81
     * ImpliesExpression ::=  LogicalExpression ( ImpliesOp ImpliesExpression | ExpliesOp LogicalExpression ( ExpliesOp LogicalExpression )* )?
     */
    ImpliesExpression: $ =>
      seq(
        $.LogicalExpression,
        optional(
          choice(
            seq($.ImpliesOp, $.ImpliesExpression),
            seq($.ExpliesOp, $.LogicalExpression, repeat(seq($.ExpliesOp, $.LogicalExpression)))
          )
        )
      ),
    /*
     * boogie.ebnf:82
     * EquivOp ::=  "<==>" | "\u21d4"
     */
    EquivOp: $ =>
      choice("<==>", "\u21d4"),
    /*
     * boogie.ebnf:83
     * LogicalExpression ::=  RelationalExpression ( AndOp RelationalExpression ( AndOp RelationalExpression )* | OrOp RelationalExpression ( OrOp RelationalExpression )* )?
     */
    LogicalExpression: $ =>
      choice(
      $.IfThenElseExpression,
      seq(
        $.RelationalExpression,
        optional(
          choice(
            seq($.AndOp, $.RelationalExpression, repeat(seq($.AndOp, $.RelationalExpression))),
            seq($.OrOp, $.RelationalExpression, repeat(seq($.OrOp, $.RelationalExpression)))
          )
        )
      )
      ),
    /*
     * boogie.ebnf:84
     * ImpliesOp ::=  "==>" | "\u21d2"
     */
    ImpliesOp: $ =>
      choice("==>", "\u21d2"),
    /*
     * boogie.ebnf:85
     * ExpliesOp ::=  "<==" | "\u21d0"
     */
    ExpliesOp: $ =>
      choice("<==", "\u21d0"),
    /*
     * boogie.ebnf:86
     * RelationalExpression ::=  BvTerm ( RelOp BvTerm )?
     */
    RelationalExpression: $ =>
      seq($.BvTerm, optional(seq($.RelOp, $.BvTerm))),
    /*
     * boogie.ebnf:87
     * AndOp ::=  "&&" | "\u2227"
     */
    AndOp: $ =>
      choice("&&", "\u2227"),
    /*
     * boogie.ebnf:88
     * OrOp ::=  "||" | "\u2228"
     */
    OrOp: $ =>
      choice("||", "\u2228"),
    /*
     * boogie.ebnf:89
     * BvTerm ::=  Term ( "++" Term )*
     */
    BvTerm: $ =>
      seq($.Term, repeat(seq("++", $.Term))),
    /*
     * boogie.ebnf:90
     * RelOp ::=  ( "==" | "<" | ">" | "<=" | ">=" | "!=" | "\u2260" | "\u2264" | "\u2265" )
     */
    RelOp: $ =>
      choice("==", "<", ">", "<=", ">=", "!=", "\u2260", "\u2264", "\u2265"),
    /*
     * boogie.ebnf:91
     * Term ::=  Factor ( AddOp Factor )*
     */
    Term: $ =>
      seq($.Factor, repeat(seq($.AddOp, $.Factor))),
    /*
     * boogie.ebnf:92
     * Factor ::=  Power ( MulOp Power )*
     */
    Factor: $ =>
      seq($.Power, repeat(seq($.MulOp, $.Power))),
    /*
     * boogie.ebnf:93
     * AddOp ::=  ( "+" | "-" )
     */
    AddOp: $ =>
      choice("+", "-"),
    /*
     * boogie.ebnf:94
     * Power ::=  IsConstructor ( "**" Power )?
     */
    Power: $ =>
      seq($.IsConstructor, optional(seq("**", $.Power))),
    /*
     * boogie.ebnf:95
     * MulOp ::=  ( "*" | "div" | "mod" | "/" )
     */
    MulOp: $ =>
      choice("*", "div", "mod", "/"),
    /*
     * boogie.ebnf:96
     * IsConstructor ::=  UnaryExpression ( "is" Ident )?
     */
    IsConstructor: $ =>
      seq($.UnaryExpression, optional(seq("is", $.Ident))),
    /*
     * boogie.ebnf:97
     * UnaryExpression ::=  ( "-" UnaryExpression | NegOp UnaryExpression | CoercionExpression )
     */
    UnaryExpression: $ =>
      choice(
        seq("-", $.UnaryExpression),
        seq($.NegOp, $.UnaryExpression),
        $.CoercionExpression
      ),
    /*
     * boogie.ebnf:98
     * NegOp ::=  "!" | "\u00ac"
     */
    NegOp: $ =>
      choice("!", "\u00ac"),
    /*
     * boogie.ebnf:99
     * CoercionExpression ::=  ArrayExpression ( ":" ( Type | Nat ) )*
     */
    CoercionExpression: $ =>
      seq($.ArrayExpression, repeat(seq(":", choice($.Type, $.Nat)))),
    /*
     * boogie.ebnf:100
     * ArrayExpression ::=  AtomExpression ( "[" ( Expression ( "," Expression )* ( ":=" Expression )? | ":=" Expression )? "]" | "->" ( Ident | "(" Ident ":=" Expression ")" ) )*
     */
    ArrayExpression: $ =>
      seq(
        $.AtomExpression,
        repeat(
          choice(
            seq(
              "[",
              optional(
                choice(
                  seq($.Expression, repeat(seq(",", $.Expression)), optional(seq(":=", $.Expression))),
                  seq(":=", $.Expression)
                )
              ),
              "]"
            ),
            seq("->", choice($.Ident, seq("(", $.Ident, ":=", $.Expression, ")")))
          )
        )
      ),
    /*
     * boogie.ebnf:101
     * Nat ::=  digits
     */
    Nat: $ =>
      $.digits,
    /*
     * boogie.ebnf:102
     * AtomExpression ::=  ( "false" | "true" | ( "roundNearestTiesToEven" | "RNE" ) | ( "roundNearestTiesToAway" | "RNA" ) | ( "roundTowardPositive" | "RTP" ) | ( "roundTowardNegative" | "RTN" ) | ( "roundTowardZero" | "RTZ" ) | Nat | Dec | Float | BvLit | string | Ident ( "(" ( Expressions )? ")" )? | "old" "(" Expression ")" | "int" "(" Expression ")" | "real" "(" Expression ")" | "(" ( Expression | Forall QuantifierBody | Exists QuantifierBody | Lambda QuantifierBody | LetExpr ) ")" | IfThenElseExpression | CodeExpression )
     */
    AtomExpression: $ =>
      choice(
        "false",
        "true",
        "roundNearestTiesToEven",
        "RNE",
        "roundNearestTiesToAway",
        "RNA",
        "roundTowardPositive",
        "RTP",
        "roundTowardNegative",
        "RTN",
        "roundTowardZero",
        "RTZ",
        $.Nat,
        $.Dec,
        $.Float,
        $.BvLit,
        $.string,
        seq($.Ident, optional(seq("(", optional($.Expressions), ")"))),
        seq("old", "(", $.Expression, ")"),
        seq("int", "(", $.Expression, ")"),
        seq("real", "(", $.Expression, ")"),
        seq(
          "(",
          choice(
            $.Expression,
            seq($.Forall, $.QuantifierBody),
            seq($.Exists, $.QuantifierBody),
            seq($.Lambda, $.QuantifierBody),
            $.LetExpr
          ),
          ")"
        ),
        $.CodeExpression
      ),
    /*
     * boogie.ebnf:103
     * Dec ::=  ( decimal | dec_float )
     */
    Dec: $ =>
      choice($.decimal, $.dec_float),
    /*
     * boogie.ebnf:104
     * Float ::=  float
     */
    Float: $ =>
      $.float,
    /*
     * boogie.ebnf:105
     * BvLit ::=  bvlit
     */
    BvLit: $ =>
      $.bvlit,
    /*
     * boogie.ebnf:106
     * Forall ::=  "forall" | "\u2200"
     */
    Forall: $ =>
      choice("forall", "\u2200"),
    /*
     * boogie.ebnf:107
     * QuantifierBody ::=  ( TypeParams BoundVars? | BoundVars ) QSep AttributeOrTrigger* Expression
     */
    QuantifierBody: $ =>
      seq(
        choice(seq($.TypeParams, optional($.BoundVars)), $.BoundVars),
        $.QSep,
        repeat($.AttributeOrTrigger),
        $.Expression
      ),
    /*
     * boogie.ebnf:108
     * Exists ::=  "exists" | "\u2203"
     */
    Exists: $ =>
      choice("exists", "\u2203"),
    /*
     * boogie.ebnf:109
     * Lambda ::=  "lambda" | "\u03bb"
     */
    Lambda: $ =>
      choice("lambda", "\u03bb"),
    /*
     * boogie.ebnf:110
     * LetExpr ::=  "var" LetVar ( "," LetVar )* ":=" Expression ( "," Expression )* ";" Attribute* Expression
     */
    LetExpr: $ =>
      seq(
        "var",
        $.LetVar,
        repeat(seq(",", $.LetVar)),
        ":=",
        $.Expression,
        repeat(seq(",", $.Expression)),
        ";",
        repeat($.Attribute),
        $.Expression
      ),
    /*
     * boogie.ebnf:111
     * IfThenElseExpression ::=  "if" Expression "then" Expression "else" Expression
     */
    IfThenElseExpression: $ =>
      seq("if", $.Expression, "then", $.Expression, "else", $.LogicalExpression),
    /*
     * boogie.ebnf:112
     * CodeExpression ::=  "|{" LocalVars* SpecBlock ( SpecBlock )* "}|"
     */
    CodeExpression: $ =>
      seq("|{", repeat($.LocalVars), $.SpecBlock, repeat($.SpecBlock), "}|"),
    /*
     * boogie.ebnf:113
     * SpecBlock ::=  Ident ":" ( LabelOrCmd )* ( "goto" Attribute* Idents | "return" Attribute* Expression ) ";"
     */
    SpecBlock: $ =>
      seq(
        $.Ident,
        ":",
        repeat($.LabelOrCmd),
        choice(
          seq("goto", repeat($.Attribute), $.Idents),
          seq("return", repeat($.Attribute), $.Expression)
        ),
        ";"
      ),
    /*
     * boogie.ebnf:114
     * AttributeOrTrigger ::=  "{" ( ":" Ident ( AttributeParameter ( "," AttributeParameter )* )? | Expression ( "," Expression )* ) "}"
     */
    AttributeOrTrigger: $ =>
      seq(
        "{",
        choice(
          seq(
            ":",
            $.Ident,
            optional(seq($.AttributeParameter, repeat(seq(",", $.AttributeParameter))))
          ),
          seq($.Expression, repeat(seq(",", $.Expression)))
        ),
        "}"
      ),
    /*
     * boogie.ebnf:115
     * AttributeParameter ::=  ( string | Expression )
     */
    AttributeParameter: $ =>
      $.Expression,
    /*
     * boogie.ebnf:116
     * QSep ::=  "::" | "\u2022"
     */
    QSep: $ =>
      choice("::", "\u2022"),
    /*
     * boogie.ebnf:117-120
     * LetVar ::=  Attribute* Ident
     * ;
     * ; tokens
     * ;
     */
    LetVar: $ =>
      seq(repeat($.Attribute), $.Ident),
    /*
     * boogie.ebnf:121
     * ident ::=  [\\]? [\u0023-$'.?A-Z^-z~] ( [\u0023-$'.?A-Z^-z~] | [0-9] )*
     */
    ident: $ =>
      regexseq(
        regexoptional(/[\\]/),
        /[\u0023-$'.?A-Z^-z~]/,
        regexrepeat(regexchoice(/[\u0023-$'.?A-Z^-z~]/, /[0-9]/))
      ),
    /*
     * boogie.ebnf:122
     * bvlit ::=  [0-9] [0-9]* [b] [v] [0-9] [0-9]*
     */
    bvlit: $ =>
      regexseq(/[0-9]/, regexrepeat(/[0-9]/), /[b]/, /[v]/, /[0-9]/, regexrepeat(/[0-9]/)),
    /*
     * boogie.ebnf:123
     * digits ::=  [0-9] [0-9]*
     */
    digits: $ =>
      regexseq(/[0-9]/, regexrepeat(/[0-9]/)),
    /*
     * boogie.ebnf:124
     * string ::=  ["] ( [\u0000-\u0009\u000b-\u000c\u000e-!\u0023-\uffff] | [\\] ["] )* ["]
     */
    string: $ =>
      regexseq(
        /["]/,
        regexrepeat(regexchoice(/[\u0000-\u0009\u000b-\u000c\u000e-!\u0023-\uffff]/, regexseq(/[\\]/, /["]/))),
        /["]/
      ),
    /*
     * boogie.ebnf:125
     * decimal ::=  [0-9] [0-9]* [e] [\u002d]? [0-9] [0-9]*
     */
    decimal: $ =>
      regexseq(/[0-9]/, regexrepeat(/[0-9]/), /[e]/, regexoptional(/[\u002d]/), /[0-9]/, regexrepeat(/[0-9]/)),
    /*
     * boogie.ebnf:126
     * dec_float ::=  [0-9] [0-9]* [.] [0-9] [0-9]* ( [e] [\u002d]? [0-9] [0-9]* )?
     */
    dec_float: $ =>
      regexseq(
        /[0-9]/,
        regexrepeat(/[0-9]/),
        /[.]/,
        /[0-9]/,
        regexrepeat(/[0-9]/),
        regexoptional(regexseq(/[e]/, regexoptional(/[\u002d]/), /[0-9]/, regexrepeat(/[0-9]/)))
      ),
    /*
     * boogie.ebnf:127
     * float ::=  [\u002d]? [0] [x] [0-9A-Fa-f] [0-9A-Fa-f]* [.] [0-9A-Fa-f] [0-9A-Fa-f]* [e] [\u002d]? [0-9] [0-9]* [f] [0-9] [0-9]* [e] [0-9] [0-9]* | [0] [N] [a] [N] [0-9] [0-9]* [e] [0-9] [0-9]* | [0] [n] [a] [n] [0-9] [0-9]* [e] [0-9] [0-9]* | [0] [+] [o] [o] [0-9] [0-9]* [e] [0-9] [0-9]* | [0] [\u002d] [o] [o] [0-9] [0-9]* [e] [0-9] [0-9]*
     */
    float: $ =>
      regexchoice(
        regexseq(
          regexoptional(/[\u002d]/),
          /[0]/,
          /[x]/,
          /[0-9A-Fa-f]/,
          regexrepeat(/[0-9A-Fa-f]/),
          /[.]/,
          /[0-9A-Fa-f]/,
          regexrepeat(/[0-9A-Fa-f]/),
          /[e]/,
          regexoptional(/[\u002d]/),
          /[0-9]/,
          regexrepeat(/[0-9]/),
          /[f]/,
          /[0-9]/,
          regexrepeat(/[0-9]/),
          /[e]/,
          /[0-9]/,
          regexrepeat(/[0-9]/)
        ),
        regexseq(
          /[0]/,
          /[N]/,
          /[a]/,
          /[N]/,
          /[0-9]/,
          regexrepeat(/[0-9]/),
          /[e]/,
          /[0-9]/,
          regexrepeat(/[0-9]/)
        ),
        regexseq(
          /[0]/,
          /[n]/,
          /[a]/,
          /[n]/,
          /[0-9]/,
          regexrepeat(/[0-9]/),
          /[e]/,
          /[0-9]/,
          regexrepeat(/[0-9]/)
        ),
        regexseq(
          /[0]/,
          /[+]/,
          /[o]/,
          /[o]/,
          /[0-9]/,
          regexrepeat(/[0-9]/),
          /[e]/,
          /[0-9]/,
          regexrepeat(/[0-9]/)
        ),
        regexseq(
          /[0]/,
          /[\u002d]/,
          /[o]/,
          /[o]/,
          /[0-9]/,
          regexrepeat(/[0-9]/),
          /[e]/,
          /[0-9]/,
          regexrepeat(/[0-9]/)
        )
      ),
    /*
     * boogie.ebnf:128
     * comment ::= /\/\/.*\n/
     */
    comment: $ =>
      /\/\/.*\n/
  }
});

