template("fetch") {

  forward_variables_from(invoker, ["strip_leading_directory", "unpack", "prefix"])

  if (!defined(strip_leading_directory)) {
    strip_leading_directory = false
  }

  if (!defined(unpack)) {
    unpack = true
  }

  if (!defined(prefix)) {
    prefix = target_gen_dir
  }

  outputs = []
  foreach(out, invoker.outputs) {
    outputs += [ "$prefix/${out}" ]
  }

  out_args = []
  foreach(out, outputs) {
    out_args += [ rebase_path(out, prefix) ]
  }

  action(target_name) {
    script = "//build/fetch.sh"
    args = [
      invoker.url,
      "$unpack",
      "$strip_leading_directory",
      rebase_path(prefix),
    ] + out_args
  }

}

