/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 21
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_char_literal = 1,
  sym_string_literal = 2,
  anon_sym_ANY = 3,
  sym_terminal_name = 4,
  anon_sym_EQ = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_PLUS = 12,
  anon_sym_DASH = 13,
  anon_sym_PIPE = 14,
  sym_grammar = 15,
  sym_rule = 16,
  sym_literal = 17,
  sym_terminal_decl = 18,
  sym_terminal_rule = 19,
  sym_terminal_atom = 20,
  sym_terminal_addition = 21,
  sym_terminal_subtraction = 22,
  sym_terminal_alternation = 23,
  sym_terminal_sequence = 24,
  aux_sym_grammar_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_char_literal] = "char_literal",
  [sym_string_literal] = "string_literal",
  [anon_sym_ANY] = "ANY",
  [sym_terminal_name] = "terminal_name",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_PIPE] = "|",
  [sym_grammar] = "grammar",
  [sym_rule] = "rule",
  [sym_literal] = "literal",
  [sym_terminal_decl] = "terminal_decl",
  [sym_terminal_rule] = "terminal_rule",
  [sym_terminal_atom] = "terminal_atom",
  [sym_terminal_addition] = "terminal_addition",
  [sym_terminal_subtraction] = "terminal_subtraction",
  [sym_terminal_alternation] = "terminal_alternation",
  [sym_terminal_sequence] = "terminal_sequence",
  [aux_sym_grammar_repeat1] = "grammar_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_char_literal] = sym_char_literal,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_ANY] = anon_sym_ANY,
  [sym_terminal_name] = sym_terminal_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_grammar] = sym_grammar,
  [sym_rule] = sym_rule,
  [sym_literal] = sym_literal,
  [sym_terminal_decl] = sym_terminal_decl,
  [sym_terminal_rule] = sym_terminal_rule,
  [sym_terminal_atom] = sym_terminal_atom,
  [sym_terminal_addition] = sym_terminal_addition,
  [sym_terminal_subtraction] = sym_terminal_subtraction,
  [sym_terminal_alternation] = sym_terminal_alternation,
  [sym_terminal_sequence] = sym_terminal_sequence,
  [aux_sym_grammar_repeat1] = aux_sym_grammar_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ANY] = {
    .visible = true,
    .named = false,
  },
  [sym_terminal_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_grammar] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal_addition] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal_subtraction] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal_alternation] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal_sequence] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_grammar_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 1,
        '\'', 5,
        '(', 14,
        ')', 15,
        '+', 20,
        '-', 21,
        '=', 13,
        'A', 3,
        '[', 16,
        ']', 17,
        '{', 18,
        '|', 22,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'N') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == 'Y') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(2);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_char_literal);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_ANY);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_terminal_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_char_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_ANY] = ACTIONS(1),
    [sym_terminal_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_grammar] = STATE(24),
    [sym_rule] = STATE(21),
    [sym_terminal_decl] = STATE(23),
    [aux_sym_grammar_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_terminal_name] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(5),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_char_literal] = ACTIONS(7),
    [sym_string_literal] = ACTIONS(7),
    [anon_sym_ANY] = ACTIONS(7),
    [sym_terminal_name] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_PIPE] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(5),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_char_literal] = ACTIONS(9),
    [sym_string_literal] = ACTIONS(9),
    [anon_sym_ANY] = ACTIONS(9),
    [sym_terminal_name] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_RBRACK] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
  },
  [STATE(4)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(5),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_char_literal] = ACTIONS(11),
    [sym_string_literal] = ACTIONS(11),
    [anon_sym_ANY] = ACTIONS(11),
    [sym_terminal_name] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(11),
  },
  [STATE(5)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(5),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_char_literal] = ACTIONS(13),
    [sym_string_literal] = ACTIONS(13),
    [anon_sym_ANY] = ACTIONS(13),
    [sym_terminal_name] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_RPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(13),
  },
  [STATE(6)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(5),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_PIPE] = ACTIONS(31),
  },
  [STATE(7)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(5),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_PIPE] = ACTIONS(31),
  },
  [STATE(8)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(5),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_PIPE] = ACTIONS(31),
  },
  [STATE(9)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(5),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_PIPE] = ACTIONS(31),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(38),
    [sym_char_literal] = ACTIONS(38),
    [sym_string_literal] = ACTIONS(38),
    [anon_sym_ANY] = ACTIONS(38),
    [sym_terminal_name] = ACTIONS(38),
    [anon_sym_LPAREN] = ACTIONS(38),
    [anon_sym_RPAREN] = ACTIONS(38),
    [anon_sym_LBRACK] = ACTIONS(38),
    [anon_sym_RBRACK] = ACTIONS(38),
    [anon_sym_LBRACE] = ACTIONS(38),
    [anon_sym_RBRACE] = ACTIONS(38),
    [anon_sym_PLUS] = ACTIONS(38),
    [anon_sym_DASH] = ACTIONS(38),
    [anon_sym_PIPE] = ACTIONS(38),
  },
  [STATE(11)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(9),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(40),
    [sym_char_literal] = ACTIONS(40),
    [sym_string_literal] = ACTIONS(40),
    [anon_sym_ANY] = ACTIONS(40),
    [sym_terminal_name] = ACTIONS(40),
    [anon_sym_LPAREN] = ACTIONS(40),
    [anon_sym_RPAREN] = ACTIONS(40),
    [anon_sym_LBRACK] = ACTIONS(40),
    [anon_sym_RBRACK] = ACTIONS(40),
    [anon_sym_LBRACE] = ACTIONS(40),
    [anon_sym_RBRACE] = ACTIONS(40),
    [anon_sym_PLUS] = ACTIONS(40),
    [anon_sym_DASH] = ACTIONS(40),
    [anon_sym_PIPE] = ACTIONS(40),
  },
  [STATE(13)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(8),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
  },
  [STATE(14)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(7),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
  },
  [STATE(15)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(6),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
  },
  [STATE(16)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(2),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(42),
    [sym_char_literal] = ACTIONS(42),
    [sym_string_literal] = ACTIONS(42),
    [anon_sym_ANY] = ACTIONS(42),
    [sym_terminal_name] = ACTIONS(42),
    [anon_sym_LPAREN] = ACTIONS(42),
    [anon_sym_RPAREN] = ACTIONS(42),
    [anon_sym_LBRACK] = ACTIONS(42),
    [anon_sym_RBRACK] = ACTIONS(42),
    [anon_sym_LBRACE] = ACTIONS(42),
    [anon_sym_RBRACE] = ACTIONS(42),
    [anon_sym_PLUS] = ACTIONS(42),
    [anon_sym_DASH] = ACTIONS(42),
    [anon_sym_PIPE] = ACTIONS(42),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(44),
    [sym_char_literal] = ACTIONS(44),
    [sym_string_literal] = ACTIONS(44),
    [anon_sym_ANY] = ACTIONS(44),
    [sym_terminal_name] = ACTIONS(44),
    [anon_sym_LPAREN] = ACTIONS(44),
    [anon_sym_RPAREN] = ACTIONS(44),
    [anon_sym_LBRACK] = ACTIONS(44),
    [anon_sym_RBRACK] = ACTIONS(44),
    [anon_sym_LBRACE] = ACTIONS(44),
    [anon_sym_RBRACE] = ACTIONS(44),
    [anon_sym_PLUS] = ACTIONS(44),
    [anon_sym_DASH] = ACTIONS(44),
    [anon_sym_PIPE] = ACTIONS(44),
  },
  [STATE(19)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(4),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
  },
  [STATE(20)] = {
    [sym_literal] = STATE(10),
    [sym_terminal_rule] = STATE(3),
    [sym_terminal_atom] = STATE(18),
    [sym_terminal_addition] = STATE(18),
    [sym_terminal_subtraction] = STATE(18),
    [sym_terminal_alternation] = STATE(18),
    [sym_terminal_sequence] = STATE(18),
    [sym_char_literal] = ACTIONS(15),
    [sym_string_literal] = ACTIONS(15),
    [anon_sym_ANY] = ACTIONS(15),
    [sym_terminal_name] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      sym_terminal_name,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_terminal_decl,
    STATE(22), 2,
      sym_rule,
      aux_sym_grammar_repeat1,
  [14] = 4,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      sym_terminal_name,
    STATE(23), 1,
      sym_terminal_decl,
    STATE(22), 2,
      sym_rule,
      aux_sym_grammar_repeat1,
  [28] = 1,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      sym_terminal_name,
  [33] = 1,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
  [37] = 1,
    ACTIONS(57), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(21)] = 0,
  [SMALL_STATE(22)] = 14,
  [SMALL_STATE(23)] = 28,
  [SMALL_STATE(24)] = 33,
  [SMALL_STATE(25)] = 37,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal_alternation, 3, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal_addition, 3, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal_subtraction, 3, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal_sequence, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal_decl, 3, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_terminal_decl, 3, 0, 0), SHIFT(10),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal_atom, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal_rule, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_terminal_rule, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grammar_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_grammar_details_md(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "grammar_details_md",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
