import("//build/lib.gni")

fetch("cocor-cpp-src") {
  url = "https://github.com/rina-forks/CocoR-CPP/archive/7ecc82e26ee6c8930a387de1fb8e8c45d9b64c7b.tar.gz"
  strip_leading_directory = true
  outputs = [
    "src/Action.cpp",
    "src/BitArray.cpp",
    "src/CharClass.cpp",
    "src/CharSet.cpp",
    "src/Coco.cpp",
    "src/Comment.cpp",
    "src/DFA.cpp",
    "src/Generator.cpp",
    "src/HashTable.cpp",
    "src/Melted.cpp",
    "src/Node.cpp",
    "src/Parser.cpp",
    "src/ParserGen.cpp",
    "src/Position.cpp",
    "src/Scanner.cpp",
    "src/SortedList.cpp",
    "src/State.cpp",
    "src/StringBuilder.cpp",
    "src/Symbol.cpp",
    "src/Tab.cpp",
    "src/Target.cpp",
  ]
}

executable("cocor-cpp") {
  sources = get_target_outputs(":cocor-cpp-src")
  deps = [ ":cocor-cpp-src" ]
}
